http:
  port: ${HTTP_PORT}
admin:
  port: ${ADMIN_PORT}
  host: ${ADMIN_HOST}
apiEndpoints:
  api:
    host: ${API_HOST}
    paths: '/ip'

  # INTERNAL REGION
  internalAuthorizer:
    host: ${INTERNAL_HOST}
    paths:
      - /authentication/sign-out

  internalCustomer:
    host: ${INTERNAL_HOST}
    paths:
      - /customers/profiles/me
      - /customers/address
      - /customers/address/me
      - /customers/avatars
      - /customers/avatars/me

  internalEmployee:
    host: ${INTERNAL_HOST}
    paths:
      - /employees/profiles/me
      - /employees/address
      - /employees/address/me
      - /employees/avatar
      - /employees/avatar/:id
      - /employees/avatar/me

  internalPet:
    host: ${INTERNAL_HOST}
    paths:
      - /pets/classifications
      - /pets/profiles/me
      - /pets/classifications/:id/races
      - /pets/:id/allergies
      - /pets/:id/avatar
      - /pets/:classification_id/allergies/:allergy_id

  internalServices:
    host: ${INTERNAL_HOST}
    paths:
      - /api/services/v1/costs
      - /api/services/v1/costs/:id
      - /api/services/v1/customers/me
      - /api/services/v1/customers/me/:id
      - /api/services/v1/customers/me/:id/cancel
      - /api/services/v1/costs/total
  
  # PUBLIC REGION
  publicAuthorizer:
    host: ${INTERNAL_HOST}
    paths:
      - /authentication/sign-in
      - /authentication/sign-up/customers

  # PRIVATE REGION
  privateAuthorizer:
    host: ${INTERNAL_HOST}
    paths:
      - /authentication/sign-up/employees
      - /authentication/account/lock

  privateCustomer:
    host: ${INTERNAL_HOST}
    paths:
      - /customers/profiles
      - /customers/profiles/:id

  privateEmployee:
    host: ${INTERNAL_HOST}
    paths:
      - /employees/profiles
      - /employees/profiles/:id
      - /employees/roles
      - /employees/roles/:id

  privateServices:
    host: ${INTERNAL_HOST}
    paths:
      - /api/services/v1/catalog
      - /api/services/v1/catalog/:id
      - /api/services/v1/customers
      - /api/services/v1/customers/:id
      - /api/services/v1/customers/:id/employee

  privatePet:
    host: ${INTERNAL_HOST}
    paths:
      - /pets/profiles
      - /pets/profiles/:id
      - /pets/classifications/:classification_id/races/:race_id
      - /pets/classifications/:id

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authorizerService:
    url: ${AUTHORIZER_URL}
  customerService:
    url: ${CUSTOMER_URL}
  employeeService:
    url: ${EMPLOYEE_URL}
  petService:
    url: ${PET_URL}
  servicesService:
    url: ${SERVICES_URL}
policies:
  - log
  - proxy
  - jwt
  - request-transformer
  - jwt-validator
  - role-validator
  - endpoint-guard
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  
  # PUBLIC REGION
  publicAuthorizerPipeline:
    apiEndpoints:
      - publicAuthorizer
    policies:
      - proxy:
          - action:
              serviceEndpoint: authorizerService
              changeOrigin: true
  
  # PRIVATE REGION
  privateAuthorizerPipeline:
    apiEndpoints:
      - privateAuthorizer
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - role-validator:
          - action:
              roles: SuperAdmin,Employee
      - proxy:
          - action:
              serviceEndpoint: authorizerService
              changeOrigin: true
  privateCustomerPipeline:
    apiEndpoints:
      - privateCustomer
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - role-validator:
          - action:
              roles: SuperAdmin,Employee
      - proxy:
          - action:
              serviceEndpoint: customerService
              changeOrigin: true
  privateEmployeePipeline:
    apiEndpoints:
      - privateEmployee
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - role-validator:
          - action:
              roles: SuperAdmin
      - proxy:
          - action:
              serviceEndpoint: employeeService
              changeOrigin: true
  privatePetPipeline:
    apiEndpoints:
      - privatePet
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - role-validator:
          - action:
              roles: SuperAdmin,Employee
      - proxy:
          - action:
              serviceEndpoint: petService
              changeOrigin: true
  privateServicesPipeline:
    apiEndpoints:
      - privateServices
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - role-validator:
          - action:
              roles: SuperAdmin,Employee
      - proxy:
          - action:
              serviceEndpoint: servicesService
              changeOrigin: true

  # INTERNAL REGION
  internalAuthorizerPipeline:
    apiEndpoints:
      - internalAuthorizer
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - proxy:
          - action:
              serviceEndpoint: authorizerService
              changeOrigin: true
  internalCustomerPipeline:
    apiEndpoints:
      - internalCustomer
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - proxy:
          - action:
              serviceEndpoint: customerService
              changeOrigin: true   
  internalEmployeePipeline:
    apiEndpoints:
      - internalEmployee
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - role-validator:
          - action:
              roles: SuperAdmin,Employee
      - proxy:
          - action:
              serviceEndpoint: employeeService
              changeOrigin: true
  internalpetPipeline:
    apiEndpoints:
      - internalPet
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - role-validator:
          - action:
              roles: SuperAdmin,Employee,Customer
      - endpoint-guard:
          - action:
              roles: Employee
              endpoints:
                - regex: \/pets\/classifications\/[^\n]+\/races$
                  methods: GET
                - regex: \/pets\/classifications
                  methods: GET
      - proxy:
          - action:
              serviceEndpoint: petService
              changeOrigin: true
  internalServicesPipeline:
    apiEndpoints:
      - internalServices
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.nameid
          - action:
              headers:
                add:
                  user-email: req.user.email
          - action:
              headers:
                add:
                  user-roles: req.user.role
      - jwt-validator:
      - endpoint-guard:
          - action:
              roles: Customer
              endpoints:
                - regex: \/api\/services\/v1\/costs$
                  methods: GET
                - regex: \/api\/services\/v1\/costs\/[a-fA-F0-9]{24}$
                  methods: GET
      - proxy:
          - action:
              serviceEndpoint: servicesService
              changeOrigin: true
